### ISSUE TITLE
Plans for PyPI release?

### ISSUE THREAD

**Issue by jezdez** [django-blog-zinnia/admin-tools-zinnia#1]
Hi there, I was wondering if you've considered publishing this on PyPI?

**Comment by Fantomas42** [comment]
Hi,

I don't know why I haven't released yet this package on Pypi, certainly an oversight...
Everything seems ok for a release, but I think that a review is needed before, especially on the packaging part, just to be sure.

So the plan for me, is to release the package tomorrow if everything is alright.

Regards

**Comment by Fantomas42** [comment]
https://pypi.python.org/pypi/admin-tools-zinnia
